// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vacation_System.Models;

namespace VactionApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("vacation_System.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthDate");

                    b.Property<string>("JobNumber");

                    b.Property<int>("MangerID");

                    b.Property<string>("Password");

                    b.Property<bool>("Status");

                    b.Property<string>("Username");

                    b.Property<int>("Vacations");

                    b.HasKey("ID");

                    b.HasIndex("MangerID");

                    b.ToTable("Employeess");
                });

            modelBuilder.Entity("vacation_System.Models.Manger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("JobNumber");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Managerss");
                });

            modelBuilder.Entity("vacation_System.Models.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("EmpID");

                    b.Property<int?>("EmployeesID");

                    b.Property<string>("Type");

                    b.Property<DateTime>("VactionDate");

                    b.HasKey("Id");

                    b.HasIndex("EmployeesID");

                    b.ToTable("Vactionss");
                });

            modelBuilder.Entity("vacation_System.Models.Employee", b =>
                {
                    b.HasOne("vacation_System.Models.Manger", "EmpManger")
                        .WithMany()
                        .HasForeignKey("MangerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("vacation_System.Models.Vacation", b =>
                {
                    b.HasOne("vacation_System.Models.Employee", "Employees")
                        .WithMany("Vacation")
                        .HasForeignKey("EmployeesID");
                });
#pragma warning restore 612, 618
        }
    }
}
